### ISSUE TITLE
Symfony 2.1/2.2/2.3/2.4 BC break

### ISSUE THREAD

**Issue by gnutix** [ma2thieu/wbxFileBundle#6]
The latest commit of this repository https://github.com/ma2thieu/wbxFileBundle/commit/4879e27a057c1c25982cbaebbe3a3c9b4e4a13e3 breaks the compatibility with Symfony versions lower than 2.5 (as the `Symfony\Component\Validator\Context\ExecutionContextInterface` interface was only added in 2.5).

Composer.json should be adapted accordingly, if that's wanted.

**Comment by ma2thieu** [comment]
Hi,
Thanks, I updated composer.json : d394f75babaecccd70dbf76518d008909ea60695

But I use `Symfony\Component\Validator\ExecutionContextInterface` not `Symfony\Component\Validator\Context\ExecutionContextInterface` so the BC break should only be for SF 2.1 and 2.2 ?

**Comment by gnutix** [comment]
Indeed! Thanks for the change.
