### ISSUE TITLE
Stable tag

### ISSUE THREAD

**Issue by gnutix** [ma2thieu/wbxFileBundle#7]
Could you please create release tags to ease Composer usage and avoid `dev-master`-related issues ?
Preferably, the following two : 

* 0.1.0 : 329dd8d0b6241e10b09ec258f0496e573721610d (supports SF 2.1+)
* 0.2.0 : 4879e27a057c1c25982cbaebbe3a3c9b4e4a13e3 (supports SF 2.5+, see https://github.com/ma2thieu/wbxFileBundle/issues/6)

Thanks a lot.

**Comment by ma2thieu** [comment]
very late but it's done
